apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 2  # Número inicial de réplicas
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: springboot-app  # Nombre de la imagen creada
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080  # Puerto que expone tu aplicación
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
