apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot-app
  minReplicas: 1  # Número mínimo de réplicas
  maxReplicas: 5  # Número máximo de réplicas
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5 #tiempo de espera para escalar hacia abajo
    scaleUp:
      stabilizationWindowSeconds: 5 #tiempo de espera para escalar hacia arriba
