apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80     # Puerto en el que el servicio escucha
      targetPort: 8080  # Puerto del contenedor
